---
# handlers file for docker

- name: check docker version
  shell: docker -version

- name: enable docker service
  shell: systemctl enable docker

- name: check docker service status
  shell: systemctl status docker

- name: restart docker 
  service:
    name: docker
    state: restarted