---
- name: Converge
  hosts: all
  tasks:
    - name: install requirements
      apt:
        name: gnupg
        state: present
        update_cache: true
    - name: "Include ansible-role-docker"
      include_role:
        name: "ansible-role-docker"
